// // This file is automatically generated. Do not edit it directly.
// import { createClient } from '@supabase/supabase-js';

// const SUPABASE_URL = "https://wtjaanvbjfirgnielcaq.supabase.co";

// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0amFhbnZiamZpcmduaWVsY2FxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYzNTgzOTcsImV4cCI6MjA5MTkzNDM5N30.PvjLDredVIClCKc58cCtx7avTXeKQ55ViRYogyzxKig";


// // Import the supabase client like this:
// // import { supabase } from "@/integrations/supabase/client";

// export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);



import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.SUPABASE_URL;
const supabaseKey = import.meta.env.SUPABASE_PUBLISHABLE_KEY;

export const supabase = createClient(supabaseUrl, supabaseKey);